used Maven, added serialization, changed dao
Rascass/HorsesClub pull request #1
Opened 2020-11-25 17:52 UTC by Rascass

I went over to Maven, added serialization/deserialization, changed my hierarchy

2020-11-25 18:55 UTC, shukal94 requested changes
make all of your models serializable
let's define all the services in the separate package
don not see any dao implementation (object or serializable class)

2020-11-25 18:55 UTC, shukal94 commented on pom.xml
> +    <maven.compiler.source>1.7</maven.compiler.source>
let's use 11

2020-11-25 21:19 UTC, Rascass commented
added database connection and changed Mochadao

2020-11-26 17:38 UTC, shukal94 approved these changes

2020-11-29 17:28 UTC, shukal94 commented on src/main/java/com/java/automation/lab/fall/antonyuk/core22/cheker/ReturnTypeValidator.java
> +public class ReturnTypeValidator {
is that date adapter?

2020-11-29 18:15 UTC, merged